version: "3"

services:
  manga-py-scheduler:
    container_name: manga-py
    build: ./
    restart: unless-stopped
    volumes:
      - ${MANGA_FOLDER}:/mangas
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SCHEDULE=${SCHEDULE}
